version: '3'

services:
  thedig:
    container_name: thedig
    image: thedig_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ${GOOGLE_CREDENTIALS}:/app/google-credentials-thedig.json:ro
    ports:
      - 8680:8080
    depends_on:
      - thedig_redis

  thedig_redis:
    image: redis:alpine
    hostname: redis
    container_name: thedig_redis
    restart: always
    command:
      - redis-server
    ports:
      - 6679:6379
