version: '3'

services:
  transmutation:
    container_name: transmutation
    image: transmutation_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - transmutation_redis

  transmutation_redis:
    image: redis:alpine
    hostname: redis
    container_name: transmutation_redis
    restart: always
    command:
      - 'redis-server'
    ports:
      - 6379:6379
