version: '3'

services:
  gemway:
    container_name: gemway
    image: gemway_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ${GOOGLE_VISION_CREDENTIALS}:/app/google-vision-gemway.json:ro
    ports:
      - "8000:8000"
    depends_on:
      - gemway_redis

  gemway_redis:
    image: redis:alpine
    hostname: redis
    container_name: gemway_redis
    restart: always
    command:
      - 'redis-server'
    ports:
      - 6379:6379
