version: '3'

services:
  app:
    container_name: transmutation
    image: transmutation_image
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - app_redis

  app_redis:
    image: redis:latest
    hostname: redis
    container_name: app_redis
    restart: always
    command:
      - 'redis-server'
    ports:
      - 6379:6379

networks:
  default:
    external: true
    name: app_main
