---
version: 1
disable_existing_loggers: true
formatters:
  default:
    format: "%(asctime)s - %(processName)s:%(process)s - %(name)s - %(levelname)s
      - %(funcName)s: %(message)s"
handlers:
  console:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: INFO
root:
  handlers:
  - console
  level: INFO
loggers:
  gunicorn:
    propagate: true
  uvicorn:
    propagate: true
  uvicorn.access:
    propagate: true
  api.config:
    propagate: true
